### ISSUE TITLE
publish to pypi

### ISSUE THREAD

**Issue by benkonrath** [benkonrath/transip-api#18]
This should be published to pypi. There is another transip library on pypi but it has been removed from github.
https://pypi.python.org/pypi/transip/0.2
https://github.com/LordGaav/python-transip

I'll probably use the `transip-api` name for pypi.

**Comment by AnalogJ** [comment]
Getting `transip-api` published on pypi would be great. I'd much rather use this library with https://github.com/AnalogJ/lexicon 
I'm running into issues with LordGaav's version (it doesn't seem to support python3), and it doesn't seem to be maintained at all anymore,  so I'll have to remove Transip support completely from Lexicon

**Comment by LordGaav** [comment]
@AnalogJ if there were problems, you should have just sent me a message.

That being said, my main goal for making my TransIP API implementation was using it with lexicon + letsencrypt.sh . I never got around to publishing the code on GitHub, and I have since moved away from that solution.

@benkonrath / @AnalogJ : I am willing to hand over the transip pypi package, but we'll have to be careful how we do it. I'm not sure how many users there are (pypi has pulled their statistics), but I want the lexicon support for TransIP to keep working.

When you're ready with a lexicon implementation, contact me and we'll work out the transfer.

**Comment by benkonrath** [comment]
@LordGaav Thanks for being willing to hand over the transip pypi package. Maybe it's better / easier for me to just publish this under the transip-api package name. That will let me get the package out sooner and it also helps lexicon transition to this package more easily.

**Comment by benkonrath** [comment]
@AnalogJ / @LordGaav Do you have an opinion on publishing this under the transip-api package name? I would have to change the python package name to transip_api to avoid a collision with LordGaav's transip package. This will impact the current users but it would be easy enough to fix.

**Comment by LordGaav** [comment]
I think you should: keep the `transip` name, rename this GIt repo to either `transip` or `python-transip`, and work with @AnalogJ in replacing my code with yours in `lexicon`. When that's ready to merge, we'll do the transition.

**Comment by benkonrath** [comment]
That seems good to me, however, I don't have extra time to work on the `lexicon` part of this transition. @AnalogJ Are you ok with this plan?

**Comment by AnalogJ** [comment]
Hey guys, 

@LordGaav, I only had 2 issues with `transip`, it had issues with python 3 (which were definitely solvable) and the fact that the source repository no longer existed, which made depending on it, and creating issues a moot point. 

@benkonrath, @LordGaav Someone already submitted a lexicon provider using @benkonrath 's transip library, it was merged in v.1.2.4. As of right now, there's no work required in `lexicon`, it should work out of the box (after an update to specify the dependency by name, rather than github repo) 

Just tell me when you guys do the hand-off & publish and I'll create a new release.

**Comment by AnalogJ** [comment]
@benkonrath, @LordGaav 
Any eta on when `transip` (or `transip-api`) will be published to pypi? The method we're using right now to pull your library is a bit kludgy.

**Comment by benkonrath** [comment]
@LordGaav I'm ready on my end. Let me know when you've transferred the account over. I'll make my first release 1 version higher than your latest release so that things don't break for people.

**Comment by LordGaav** [comment]
@benkonrath what is your PyPi username?

**Comment by benkonrath** [comment]
@LordGaav My PyPi username is `bkonrath`.

**Comment by LordGaav** [comment]
@benkonrath I've added you as extra Owner on the PyPi repo.

**Comment by benkonrath** [comment]
This package is now on pypi as transip 0.3.0.

@LordGaav Let me know if you want me to remove you as the owner on pypi.
