### ISSUE TITLE
New API version

### ISSUE THREAD

**Issue by marklagendijk** [benkonrath/transip-api#61]
Just wanted to give you a heads-up, TransIP has released a [new version of their API](https://api.transip.nl/rest/docs.html#introduction).
Good news: the API is a nice REST API that is way simpler to use than the previous sort-of-soap-based API. So this library would be a lot simpler when it uses the new API. 
Bad news:  this library needs to be updated.

I created [transip-dns-cli](https://github.com/marklagendijk/node-transip-dns-cli) with this new API. If you want to update this library to the new API, you may find [this](https://github.com/marklagendijk/node-transip-dns-cli/blob/master/lib/api.js) helpful (especially the implementation of the token request, because that is not so well documented).

**Comment by olafz** [comment]
See also https://github.com/benkonrath/transip-api/issues/60

**Comment by meeuw** [comment]
I've found these other Python projects implementing the TransIP REST API:

https://github.com/mathijswesterhof/TransIp_Rest_api_python
https://github.com/startmail/transip_rest_client

Would it make sense to update this project to the REST API?

**Comment by benkonrath** [comment]
If there's already a solid implementation wrapping the REST API in Python then updating this library doesn't for the REST API probably doesn't make sense.

In any case, I don't have a lot of extra time right now and I don't really use TransIP these days so I'd likely not update it any time soon. I'm definitely open to somebody taking on the work if they feel that it's worthwhile.

**Comment by roaldnefs** [comment]
I'm currently working on a new Python client for the TransIP REST API (v6) called [`python-transip`](https://github.com/roaldnefs/python-transip). It's far from being a solid implementation yet, but the [quick-start instructions](https://python-transip.readthedocs.io/en/latest/user/quickstart.html) should give an impressions of its current capabilities.

Instead of having to fully implement each and every endpoint, I'm trying to implement a more dynamic way to allow each resource/service to inherit from a set of mixins that provide more discrete functionality. This should allow for easier and faster implementing of the currently still missing endpoints. See the [`DomainService`](https://github.com/roaldnefs/python-transip/blob/master/transip/v6/services/domain.py#L27) (_used to query the `/domains` endpoint_) for example.

Please file an issue if you are missing something, or would like to have a specific endpoint to be implemented with a higher priority. Any help is appreciated!

**Comment by benkonrath** [comment]
Thanks @roaldnefs! Feel free to add a link in the README to your library.

You can also mark this library as depreciated when you think your library is ready. It might be worthwhile to reach out to some of our users to inform them that they should consider updating to your library:
https://github.com/benkonrath/transip-api/network/dependents

Thanks for working this!
